hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_sber
    username: postgres
    password: arsen1995
  default_schema: Client
  show_sql: true
  enable_lazy_load_no_trans: true
  ddl_auto: update

